TableGamePageMapXpath = dict (
#AcceptCookies="[data-hook='acceptcookies']",
    #PlayforFun="[data-hook='live-casino-play-now']",
    a_To_z="[data-hook='casino-sortaz']",
    z_To_a="[data-hook='casino-sortza']",
    TableGameImage1="[data-hook='game-image1']",
    TableGameImage2="[data-hook='game-image2']",
    TableGameImage3="[data-hook='game-image3']",
    TableGameImage4="[data-hook='game-image4']",
    TableGameImage5="[data-hook='game-image5']",
    TableGameImage6="[data-hook='game-image6']",
    TableGameImage7="[data-hook='game-image7']",
    TableGameImage8="[data-hook='game-image8']",
    TableGameImage9="[data-hook='game-image9']",
    TableGameImage10="[data-hook='game-image10']",
    TableGameImage11="[data-hook='game-image11']",
    TableGameImage12="[data-hook='game-image12']",
    TableGameImage13="[data-hook='game-image13']",
    TableGameImage14="[data-hook='game-image14']",
    TableGameImage15="[data-hook='game-image15']",
    TableGameImage16="[data-hook='game-image16']",
    TableGameImage17="[data-hook='game-image17']",
    TableGameImage18="[data-hook='game-image18']",
    TableGameImage19="[data-hook='game-image19']",
    TableGameImage20="[data-hook='game-image20']",
    TableGameImage21="[data-hook='game-image21']",
    TableGameImage22="[data-hook='game-image22']",
    TableGameImage23="[data-hook='game-image23']",
    TableGameImage24="[data-hook='game-image24']",
    TableGameImage25="[data-hook='game-image25']",
    TableGameImage26="[data-hook='game-image26']",
    TableGameImage27="[data-hook='game-image27']",
    TableGameImage28="[data-hook='game-image28']",
    TableGameImage29="[data-hook='game-image29']",
    TableGameImage30="[data-hook='game-image30']",
    TableGameImage31="[data-hook='game-image31']",
    TableGameImage32="[data-hook='game-image32']",
    TableGameImage33="[data-hook='game-image33']",
    TableGameImage34="[data-hook='game-image34']",
    TableGameImage35="[data-hook='game-image35']",
    TableGameImage36="[data-hook='game-image36']",
    TableGameImage37="[data-hook='game-image37']",
    TableGameImage38="[data-hook='game-image38']",
    TableGameImage39="[data-hook='game-image39']",
    TableGameImage40="[data-hook='game-image40']",
    TableGameImage41="[data-hook='game-image41']",
    TableGameImage42="[data-hook='game-image42']",
    TableGameImage43="[data-hook='game-image43']",
    TableGameImage44="[data-hook='game-image44']",
    TableGameImage45="[data-hook='game-image45']",
    TableGameImage46="[data-hook='game-image46']",
    TableGameImage47="[data-hook='game-image47']",
    TableGameImage48="[data-hook='game-image48']",
    TableGameImage49="[data-hook='game-image49']",
    TableGameImage50="[data-hook='game-image50']",
    TableGamename1="[data-hook='game-name1']",
    TableGamename2="[data-hook='game-name2']",
    TableGamename3="[data-hook='game-name3']",
    TableGamename4="[data-hook='game-name4']",
    TableGamename5="[data-hook='game-name5']",
    TableGamename6="[data-hook='game-name6']",
    TableGamename7="[data-hook='game-name7']",
    TableGamename8="[data-hook='game-name8']",
    TableGamename9="[data-hook='game-name9']",
    TableGamename10="[data-hook='game-name10']",
    TableGamename11="[data-hook='game-name11']",
    TableGamename12="[data-hook='game-name12']",
    TableGamename13="[data-hook='game-name13']",
    TableGamename14="[data-hook='game-name14']",
    TableGamename15="[data-hook='game-name15']",
    TableGamename16="[data-hook='game-name16']",
    TableGamename17="[data-hook='game-name17']",
    TableGamename18="[data-hook='game-name18']",
    TableGamename19="[data-hook='game-name19']",
    TableGamename20="[data-hook='game-name20']",
    TableGamename21="[data-hook='game-name21']",
    TableGamename22="[data-hook='game-name22']",
    TableGamename23="[data-hook='game-name23']",
    TableGamename24="[data-hook='game-name24']",
    TableGamename25="[data-hook='game-name25']",
    TableGamename26="[data-hook='game-name26']",
    TableGamename27="[data-hook='game-name27']",
    TableGamename28="[data-hook='game-name28']",
    TableGamename29="[data-hook='game-name29']",
    TableGamename30="[data-hook='game-name30']",
    TableGamename31="[data-hook='game-name31']",
    TableGamename32="[data-hook='game-name32']",
    TableGamename33="[data-hook='game-name33']",
    TableGamename34="[data-hook='game-name34']",
    TableGamename35="[data-hook='game-name35']",
    TableGamename36="[data-hook='game-name36']",
    TableGamename37="[data-hook='game-name37']",
    TableGamename38="[data-hook='game-name38']",
    TableGamename39="[data-hook='game-name39']",
    TableGamename40="[data-hook='game-name40']",
    TableGamename41="[data-hook='game-name41']",
    TableGamename42="[data-hook='game-name42']",
    TableGamename43="[data-hook='game-name43']",
    TableGamename44="[data-hook='game-name44']",
    TableGamename45="[data-hook='game-name45']",
    TableGamename46="[data-hook='game-name46']",
    TableGamename47="[data-hook='game-name47']",
    TableGamename48="[data-hook='game-name48']",
    TableGamename49="[data-hook='game-name49']",
    TableGamename50="[data-hook='game-name50']",

)
TableGamePageMaptype = dict(

Tgtype1  =  "[data-hook='game-type1']",
Tgtype2  =  "[data-hook='game-type2']",
Tgtype3  =  "[data-hook='game-type3']",
Tgtype4  =  "[data-hook='game-type4']",
Tgtype5  =  "[data-hook='game-type5']",
Tgtype6  =  "[data-hook='game-type6']",
Tgtype7  =  "[data-hook='game-type7']",
Tgtype8  =  "[data-hook='game-type8']",
Tgtype9  =  "[data-hook='game-type9']",
Tgtype10  =  "[data-hook='game-type10']",
Tgtype11  =  "[data-hook='game-type11']",
Tgtype12  =  "[data-hook='game-type12']",
Tgtype13  =  "[data-hook='game-type13']",
Tgtype14  =  "[data-hook='game-type14']",
Tgtype15  =  "[data-hook='game-type15']",
Tgtype16  =  "[data-hook='game-type16']",
Tgtype17  =  "[data-hook='game-type17']",
Tgtype18  =  "[data-hook='game-type18']",
Tgtype19  =  "[data-hook='game-type19']",
Tgtype20  =  "[data-hook='game-type20']",
Tgtype21  =  "[data-hook='game-type21']",
Tgtype22  =  "[data-hook='game-type22']",
Tgtype23  =  "[data-hook='game-type23']",
Tgtype24  =  "[data-hook='game-type24']",
Tgtype25  =  "[data-hook='game-type25']",
Tgtype26  =  "[data-hook='game-type26']",
Tgtype27  =  "[data-hook='game-type27']",
Tgtype28  =  "[data-hook='game-type28']",
Tgtype29  =  "[data-hook='game-type29']",
Tgtype30  =  "[data-hook='game-type30']",
Tgtype31  =  "[data-hook='game-type31']",
Tgtype32  =  "[data-hook='game-type32']",
Tgtype33  =  "[data-hook='game-type33']",
Tgtype34  =  "[data-hook='game-type34']",
Tgtype35  =  "[data-hook='game-type35']",
Tgtype36  =  "[data-hook='game-type36']",
Tgtype37  =  "[data-hook='game-type37']",
Tgtype38  =  "[data-hook='game-type38']",
Tgtype39  =  "[data-hook='game-type39']",
Tgtype40  =  "[data-hook='game-type40']",
Tgtype41  =  "[data-hook='game-type41']",
Tgtype42  =  "[data-hook='game-type42']",
Tgtype43  =  "[data-hook='game-type43']",
Tgtype44  =  "[data-hook='game-type44']",
Tgtype45  =  "[data-hook='game-type45']",
Tgtype46  =  "[data-hook='game-type46']",
Tgtype47  =  "[data-hook='game-type47']",
Tgtype48  =  "[data-hook='game-type48']",
Tgtype49  =  "[data-hook='game-type49']",
Tgtype50  =  "[data-hook='game-type50']",




)