VideoPokerGamePageMapXpath = dict (
#AcceptCookies="[data-hook='acceptcookies']",
    a_To_z="[data-hook='casino-sortaz']",
    z_To_a="[data-hook='casino-sortza']",
#videopokergameimage1

VideoPokerGameImage1   =  "[data-hook='game-image1']",
VideoPokerGameImage2   =  "[data-hook='game-image2']",
VideoPokerGameImage3   =  "[data-hook='game-image3']",
VideoPokerGameImage4   =  "[data-hook='game-image4']",
VideoPokerGameImage5   =  "[data-hook='game-image5']",
VideoPokerGameImage6   =  "[data-hook='game-image6']",
VideoPokerGameImage7   =  "[data-hook='game-image7']",
VideoPokerGameImage8   =  "[data-hook='game-image8']",
VideoPokerGameImage9   =  "[data-hook='game-image9']",
VideoPokerGameImage10   =  "[data-hook='game-image10']",
VideoPokerGameImage11   =  "[data-hook='game-image11']",
VideoPokerGameImage12   =  "[data-hook='game-image12']",
VideoPokerGameImage13   =  "[data-hook='game-image13']",
VideoPokerGameImage14   =  "[data-hook='game-image14']",
VideoPokerGameImage15   =  "[data-hook='game-image15']",
VideoPokerGameImage16   =  "[data-hook='game-image16']",
VideoPokerGameImage17   =  "[data-hook='game-image17']",
VideoPokerGameImage18   =  "[data-hook='game-image18']",
VideoPokerGameImage19   =  "[data-hook='game-image19']",
VideoPokerGameImage20   =  "[data-hook='game-image20']",
VideoPokerGameImage21   =  "[data-hook='game-image21']",
VideoPokerGameImage22   =  "[data-hook='game-image22']",
VideoPokerGameImage23   =  "[data-hook='game-image23']",
VideoPokerGameImage24   =  "[data-hook='game-image24']",
VideoPokerGameImage25   =  "[data-hook='game-image25']",
VideoPokerGameImage26   =  "[data-hook='game-image26']",
VideoPokerGameImage27   =  "[data-hook='game-image27']",
VideoPokerGameImage28   =  "[data-hook='game-image28']",
VideoPokerGameImage29   =  "[data-hook='game-image29']",
VideoPokerGameImage30   =  "[data-hook='game-image30']",
VideoPokerGameImage31   =  "[data-hook='game-image31']",
VideoPokerGameImage32   =  "[data-hook='game-image32']",
VideoPokerGameImage33   =  "[data-hook='game-image33']",
VideoPokerGameImage34   =  "[data-hook='game-image34']",
VideoPokerGameImage35   =  "[data-hook='game-image35']",
VideoPokerGameImage36   =  "[data-hook='game-image36']",
VideoPokerGameImage37   =  "[data-hook='game-image37']",
VideoPokerGameImage38   =  "[data-hook='game-image38']",
VideoPokerGameImage39   =  "[data-hook='game-image39']",
VideoPokerGameImage40   =  "[data-hook='game-image40']",
VideoPokerGameImage41   =  "[data-hook='game-image41']",
VideoPokerGameImage42   =  "[data-hook='game-image42']",
VideoPokerGameImage43   =  "[data-hook='game-image43']",
VideoPokerGameImage44   =  "[data-hook='game-image44']",
VideoPokerGameImage45   =  "[data-hook='game-image45']",
VideoPokerGameImage46   =  "[data-hook='game-image46']",
VideoPokerGameImage47   =  "[data-hook='game-image47']",
VideoPokerGameImage48   =  "[data-hook='game-image48']",
VideoPokerGameImage49   =  "[data-hook='game-image49']",
VideoPokerGameImage50   =  "[data-hook='game-image50']",
VideoPokerGamename1="[data-hook='game-name1']",
VideoPokerGamename2="[data-hook='game-name2']",
VideoPokerGamename3="[data-hook='game-name3']",
VideoPokerGamename4="[data-hook='game-name4']",
VideoPokerGamename5="[data-hook='game-name5']",
VideoPokerGamename6="[data-hook='game-name6']",
VideoPokerGamename7="[data-hook='game-name7']",
VideoPokerGamename8="[data-hook='game-name8']",
VideoPokerGamename9="[data-hook='game-name9']",
VideoPokerGamename10="[data-hook='game-name10']",
VideoPokerGamename11="[data-hook='game-name11']",
VideoPokerGamename12="[data-hook='game-name12']",
VideoPokerGamename13="[data-hook='game-name13']",
VideoPokerGamename14="[data-hook='game-name14']",
VideoPokerGamename15="[data-hook='game-name15']",
VideoPokerGamename16="[data-hook='game-name16']",
VideoPokerGamename17="[data-hook='game-name17']",
VideoPokerGamename18="[data-hook='game-name18']",
VideoPokerGamename19="[data-hook='game-name19']",
VideoPokerGamename20="[data-hook='game-name20']",
VideoPokerGamename21="[data-hook='game-name21']",
VideoPokerGamename22="[data-hook='game-name22']",
VideoPokerGamename23="[data-hook='game-name23']",
VideoPokerGamename24="[data-hook='game-name24']",
VideoPokerGamename25="[data-hook='game-name25']",
VideoPokerGamename26="[data-hook='game-name26']",
VideoPokerGamename27="[data-hook='game-name27']",
VideoPokerGamename28="[data-hook='game-name28']",
VideoPokerGamename29="[data-hook='game-name29']",
VideoPokerGamename30="[data-hook='game-name30']",
VideoPokerGamename31="[data-hook='game-name31']",
VideoPokerGamename32="[data-hook='game-name32']",
VideoPokerGamename33="[data-hook='game-name33']",
VideoPokerGamename34="[data-hook='game-name34']",
VideoPokerGamename35="[data-hook='game-name35']",
VideoPokerGamename36="[data-hook='game-name36']",
VideoPokerGamename37="[data-hook='game-name37']",
VideoPokerGamename38="[data-hook='game-name38']",
VideoPokerGamename39="[data-hook='game-name39']",
VideoPokerGamename40="[data-hook='game-name40']",
VideoPokerGamename41="[data-hook='game-name41']",
VideoPokerGamename42="[data-hook='game-name42']",
VideoPokerGamename43="[data-hook='game-name43']",
VideoPokerGamename44="[data-hook='game-name44']",
VideoPokerGamename45="[data-hook='game-name45']",
VideoPokerGamename46="[data-hook='game-name46']",
VideoPokerGamename47="[data-hook='game-name47']",
VideoPokerGamename48="[data-hook='game-name48']",
VideoPokerGamename49="[data-hook='game-name49']",
VideoPokerGamename50="[data-hook='game-name50']"
)
VideoPokerGamePageMaptype = dict(
Vgtype1  =  "[data-hook='game-type1']",
Vgtype2  =  "[data-hook='game-type2']",
Vgtype3  =  "[data-hook='game-type3']",
Vgtype4  =  "[data-hook='game-type4']",
Vgtype5  =  "[data-hook='game-type5']",
Vgtype6  =  "[data-hook='game-type6']",
Vgtype7  =  "[data-hook='game-type7']",
Vgtype8  =  "[data-hook='game-type8']",
Vgtype9  =  "[data-hook='game-type9']",
Vgtype10  =  "[data-hook='game-type10']",
Vgtype11  =  "[data-hook='game-type11']",
Vgtype12  =  "[data-hook='game-type12']",
Vgtype13  =  "[data-hook='game-type13']",
Vgtype14  =  "[data-hook='game-type14']",
Vgtype15  =  "[data-hook='game-type15']",
Vgtype16  =  "[data-hook='game-type16']",
Vgtype17  =  "[data-hook='game-type17']",
Vgtype18  =  "[data-hook='game-type18']",
Vgtype19  =  "[data-hook='game-type19']",
Vgtype20  =  "[data-hook='game-type20']",
Vgtype21  =  "[data-hook='game-type21']",
Vgtype22  =  "[data-hook='game-type22']",
Vgtype23  =  "[data-hook='game-type23']",
Vgtype24  =  "[data-hook='game-type24']",
Vgtype25  =  "[data-hook='game-type25']",
Vgtype26  =  "[data-hook='game-type26']",
Vgtype27  =  "[data-hook='game-type27']",
Vgtype28  =  "[data-hook='game-type28']",
Vgtype29  =  "[data-hook='game-type29']",
Vgtype30  =  "[data-hook='game-type30']",
Vgtype31  =  "[data-hook='game-type31']",
Vgtype32  =  "[data-hook='game-type32']",
Vgtype33  =  "[data-hook='game-type33']",
Vgtype34  =  "[data-hook='game-type34']",
Vgtype35  =  "[data-hook='game-type35']",
Vgtype36  =  "[data-hook='game-type36']",
Vgtype37  =  "[data-hook='game-type37']",
Vgtype38  =  "[data-hook='game-type38']",
Vgtype39  =  "[data-hook='game-type39']",
Vgtype40  =  "[data-hook='game-type40']",
Vgtype41  =  "[data-hook='game-type41']",
Vgtype42  =  "[data-hook='game-type42']",
Vgtype43  =  "[data-hook='game-type43']",
Vgtype44  =  "[data-hook='game-type44']",
Vgtype45  =  "[data-hook='game-type45']",
Vgtype46  =  "[data-hook='game-type46']",
Vgtype47  =  "[data-hook='game-type47']",
Vgtype48  =  "[data-hook='game-type48']",
Vgtype49  =  "[data-hook='game-type49']",
Vgtype50  =  "[data-hook='game-type50']",



)