#Change on January 24, 2019
LiveCasinoPageMap = dict(
                          AcceptCookies="[data-hook='acceptcookies']",  #
                          livecasinoLocatortop="[data-hook='livecasino-top']",#
                          LiveLobby="[data-hook='live-casino-lobby-menu']",#
                          LiveRoulette ="[data-hook='live-casino-roulette-menu']",#
                          LiveBlackjack="[data-hook='live-casino-blackjack-menu']",#
                          LiveBaccarat="[data-hook='live-casino-baccarat-menu']",#
                          LivePoker="[data-hook='live-casino-poker-menu']",#
                          LiveOthers ="[data-hook='live-casino-other-menu']",
                          LivePlaynow ="[data-hook='live-casino-play-now']",
    ProviderLog1="[data-hook='live-casino-game-provider1']",
    ProviderLog2="[data-hook='live-casino-game-provider2']",
    ProviderLog3="[data-hook='live-casino-game-provider3']",
    ProviderLog4="[data-hook='live-casino-game-provider4']",
    ProviderLog5="[data-hook='live-casino-game-provider5']",
    ProviderLog6="[data-hook='live-casino-game-provider6']",
    ProviderLog7="[data-hook='live-casino-game-provider7']",
    ProviderLog8="[data-hook='live-casino-game-provider8']",
    ProviderLog9="[data-hook='live-casino-game-provider9']",
    ProviderLog10="[data-hook='live-casino-game-provider10']",
    ProviderLog11="[data-hook='live-casino-game-provider11']",
    ProviderLog12="[data-hook='live-casino-game-provider12']",
    ProviderLog13="[data-hook='live-casino-game-provider13']",
    ProviderLog14="[data-hook='live-casino-game-provider14']",
    ProviderLog15="[data-hook='live-casino-game-provider15']",
    ProviderLog16="[data-hook='live-casino-game-provider16']",
    ProviderLog17="[data-hook='live-casino-game-provider17']",
    ProviderLog18="[data-hook='live-casino-game-provider18']",
    ProviderLog19="[data-hook='live-casino-game-provider19']",
    ProviderLog20="[data-hook='live-casino-game-provider20']",
    ProviderLog21="[data-hook='live-casino-game-provider21']",
    ProviderLog22="[data-hook='live-casino-game-provider22']",
    ProviderLog23="[data-hook='live-casino-game-provider23']",
    ProviderLog24="[data-hook='live-casino-game-provider24']",
    ProviderLog25="[data-hook='live-casino-game-provider25']",
    ProviderLog26="[data-hook='live-casino-game-provider26']",
    ProviderLog27="[data-hook='live-casino-game-provider27']",
    ProviderLog28="[data-hook='live-casino-game-provider28']",
    ProviderLog29="[data-hook='live-casino-game-provider29']",
    ProviderLog30="[data-hook='live-casino-game-provider30']",
    ProviderLog31="[data-hook='live-casino-game-provider31']",
    ProviderLog32="[data-hook='live-casino-game-provider32']",
    ProviderLog33="[data-hook='live-casino-game-provider33']",
    ProviderLog34="[data-hook='live-casino-game-provider34']",
    ProviderLog35="[data-hook='live-casino-game-provider35']",
    ProviderLog36="[data-hook='live-casino-game-provider36']",
    ProviderLog37="[data-hook='live-casino-game-provider37']",
    ProviderLog38="[data-hook='live-casino-game-provider38']",
    ProviderLog39="[data-hook='live-casino-game-provider39']",
    ProviderLog40="[data-hook='live-casino-game-provider40']",
    ProviderLog41="[data-hook='live-casino-game-provider41']",
    ProviderLog42="[data-hook='live-casino-game-provider42']",
    ProviderLog43="[data-hook='live-casino-game-provider43']",
    ProviderLog44="[data-hook='live-casino-game-provider44']",
    ProviderLog45="[data-hook='live-casino-game-provider45']",
    ProviderLog46="[data-hook='live-casino-game-provider46']",
    ProviderLog47="[data-hook='live-casino-game-provider47']",
    ProviderLog48="[data-hook='live-casino-game-provider48']",
    ProviderLog49="[data-hook='live-casino-game-provider49']",
    ProviderLog50="[data-hook='live-casino-game-provider50']",

    #live game name under images
    Livegname1="[data-hook='live-casino-game-name1']",
    Livegname2="[data-hook='live-casino-game-name2']",
    Livegname3="[data-hook='live-casino-game-name3']",
    Livegname4="[data-hook='live-casino-game-name4']",
    Livegname5="[data-hook='live-casino-game-name5']",
    Livegname6="[data-hook='live-casino-game-name6']",
    Livegname7="[data-hook='live-casino-game-name7']",
    Livegname8="[data-hook='live-casino-game-name8']",
    Livegname9="[data-hook='live-casino-game-name9']",
    Livegname10="[data-hook='live-casino-game-name10']",
    Livegname11="[data-hook='live-casino-game-name11']",
    Livegname12="[data-hook='live-casino-game-name12']",
    Livegname13="[data-hook='live-casino-game-name13']",
    Livegname14="[data-hook='live-casino-game-name14']",
    Livegname15="[data-hook='live-casino-game-name15']",
    Livegname16="[data-hook='live-casino-game-name16']",
    Livegname17="[data-hook='live-casino-game-name17']",
    Livegname18="[data-hook='live-casino-game-name18']",
    Livegname19="[data-hook='live-casino-game-name19']",
    Livegname20="[data-hook='live-casino-game-name20']",
    Livegname21="[data-hook='live-casino-game-name21']",
    Livegname22="[data-hook='live-casino-game-name22']",
    Livegname23="[data-hook='live-casino-game-name23']",
    Livegname24="[data-hook='live-casino-game-name24']",
    Livegname25="[data-hook='live-casino-game-name25']",
    Livegname26="[data-hook='live-casino-game-name26']",
    Livegname27="[data-hook='live-casino-game-name27']",
    Livegname28="[data-hook='live-casino-game-name28']",
    Livegname29="[data-hook='live-casino-game-name29']",
    Livegname30="[data-hook='live-casino-game-name30']",
    Livegname31="[data-hook='live-casino-game-name31']",
    Livegname32="[data-hook='live-casino-game-name32']",
    Livegname33="[data-hook='live-casino-game-name33']",
    Livegname34="[data-hook='live-casino-game-name34']",
    Livegname35="[data-hook='live-casino-game-name35']",
    Livegname36="[data-hook='live-casino-game-name36']",
    Livegname37="[data-hook='live-casino-game-name37']",
    Livegname38="[data-hook='live-casino-game-name38']",
    Livegname39="[data-hook='live-casino-game-name39']",
    Livegname40="[data-hook='live-casino-game-name40']",
    Livegname41="[data-hook='live-casino-game-name41']",
    Livegname42="[data-hook='live-casino-game-name42']",
    Livegname43="[data-hook='live-casino-game-name43']",
    Livegname44="[data-hook='live-casino-game-name44']",
    Livegname45="[data-hook='live-casino-game-name45']",
    Livegname46="[data-hook='live-casino-game-name46']",
    Livegname47="[data-hook='live-casino-game-name47']",
    Livegname48="[data-hook='live-casino-game-name48']",
    Livegname49="[data-hook='live-casino-game-name49']",
    Livegname50="[data-hook='live-casino-game-name50']",
    #live-casino-game-limits2
    Livegminmax1="[data-hook='live-casino-game-limits1']",
    Livegminmax2="[data-hook='live-casino-game-limits2']",
    Livegminmax3="[data-hook='live-casino-game-limits3']",
    Livegminmax4="[data-hook='live-casino-game-limits4']",
    Livegminmax5="[data-hook='live-casino-game-limits5']",
    Livegminmax6="[data-hook='live-casino-game-limits6']",
    Livegminmax7="[data-hook='live-casino-game-limits7']",
    Livegminmax8="[data-hook='live-casino-game-limits8']",
    Livegminmax9="[data-hook='live-casino-game-limits9']",
    Livegminmax10="[data-hook='live-casino-game-limits10']",
    Livegminmax11="[data-hook='live-casino-game-limits11']",
    Livegminmax12="[data-hook='live-casino-game-limits12']",
    Livegminmax13="[data-hook='live-casino-game-limits13']",
    Livegminmax14="[data-hook='live-casino-game-limits14']",
    Livegminmax15="[data-hook='live-casino-game-limits15']",
    Livegminmax16="[data-hook='live-casino-game-limits16']",
    Livegminmax17="[data-hook='live-casino-game-limits17']",
    Livegminmax18="[data-hook='live-casino-game-limits18']",
    Livegminmax19="[data-hook='live-casino-game-limits19']",
    Livegminmax20="[data-hook='live-casino-game-limits20']",
    Livegminmax21="[data-hook='live-casino-game-limits21']",
    Livegminmax22="[data-hook='live-casino-game-limits22']",
    Livegminmax23="[data-hook='live-casino-game-limits23']",
    Livegminmax24="[data-hook='live-casino-game-limits24']",
    Livegminmax25="[data-hook='live-casino-game-limits25']",
    Livegminmax26="[data-hook='live-casino-game-limits26']",
    Livegminmax27="[data-hook='live-casino-game-limits27']",
    Livegminmax28="[data-hook='live-casino-game-limits28']",
    Livegminmax29="[data-hook='live-casino-game-limits29']",
    Livegminmax30="[data-hook='live-casino-game-limits30']",
    Livegminmax31="[data-hook='live-casino-game-limits31']",
    Livegminmax32="[data-hook='live-casino-game-limits32']",
    Livegminmax33="[data-hook='live-casino-game-limits33']",
    Livegminmax34="[data-hook='live-casino-game-limits34']",
    Livegminmax35="[data-hook='live-casino-game-limits35']",
    Livegminmax36="[data-hook='live-casino-game-limits36']",
    Livegminmax37="[data-hook='live-casino-game-limits37']",
    Livegminmax38="[data-hook='live-casino-game-limits38']",
    Livegminmax39="[data-hook='live-casino-game-limits39']",
    Livegminmax40="[data-hook='live-casino-game-limits40']",
    Livegminmax41="[data-hook='live-casino-game-limits41']",
    Livegminmax42="[data-hook='live-casino-game-limits42']",
    Livegminmax43="[data-hook='live-casino-game-limits43']",
    Livegminmax44="[data-hook='live-casino-game-limits44']",
    Livegminmax45="[data-hook='live-casino-game-limits45']",
    Livegminmax46="[data-hook='live-casino-game-limits46']",
    Livegminmax47="[data-hook='live-casino-game-limits47']",
    Livegminmax48="[data-hook='live-casino-game-limits48']",
    Livegminmax49="[data-hook='live-casino-game-limits49']",
    Livegminmax50="[data-hook='live-casino-game-limits50']",

    LiveDealername1="[data-hook='live-casino-game-dealer-name1']",
    LiveDealername2="[data-hook='live-casino-game-dealer-name2']",
    LiveDealername3="[data-hook='live-casino-game-dealer-name3']",
    LiveDealername4="[data-hook='live-casino-game-dealer-name4']",
    LiveDealername5="[data-hook='live-casino-game-dealer-name5']",
    LiveDealername6="[data-hook='live-casino-game-dealer-name6']",
    LiveDealername7="[data-hook='live-casino-game-dealer-name7']",
    LiveDealername8="[data-hook='live-casino-game-dealer-name8']",
    LiveDealername9="[data-hook='live-casino-game-dealer-name9']",
    LiveDealername10="[data-hook='live-casino-game-dealer-name10']",
    LiveDealername11="[data-hook='live-casino-game-dealer-name11']",
    LiveDealername12="[data-hook='live-casino-game-dealer-name12']",
    LiveDealername13="[data-hook='live-casino-game-dealer-name13']",
    LiveDealername14="[data-hook='live-casino-game-dealer-name14']",
    LiveDealername15="[data-hook='live-casino-game-dealer-name15']",
    LiveDealername16="[data-hook='live-casino-game-dealer-name16']",
    LiveDealername17="[data-hook='live-casino-game-dealer-name17']",
    LiveDealername18="[data-hook='live-casino-game-dealer-name18']",
    LiveDealername19="[data-hook='live-casino-game-dealer-name19']",
    LiveDealername20="[data-hook='live-casino-game-dealer-name20']",
    LiveDealername21="[data-hook='live-casino-game-dealer-name21']",
    LiveDealername22="[data-hook='live-casino-game-dealer-name22']",
    LiveDealername23="[data-hook='live-casino-game-dealer-name23']",
    LiveDealername24="[data-hook='live-casino-game-dealer-name24']",
    LiveDealername25="[data-hook='live-casino-game-dealer-name25']",
    LiveDealername26="[data-hook='live-casino-game-dealer-name26']",
    LiveDealername27="[data-hook='live-casino-game-dealer-name27']",
    LiveDealername28="[data-hook='live-casino-game-dealer-name28']",
    LiveDealername29="[data-hook='live-casino-game-dealer-name29']",
    LiveDealername30="[data-hook='live-casino-game-dealer-name30']",
    LiveDealername31="[data-hook='live-casino-game-dealer-name31']",
    LiveDealername32="[data-hook='live-casino-game-dealer-name32']",
    LiveDealername33="[data-hook='live-casino-game-dealer-name33']",
    LiveDealername34="[data-hook='live-casino-game-dealer-name34']",
    LiveDealername35="[data-hook='live-casino-game-dealer-name35']",
    LiveDealername36="[data-hook='live-casino-game-dealer-name36']",
    LiveDealername37="[data-hook='live-casino-game-dealer-name37']",
    LiveDealername38="[data-hook='live-casino-game-dealer-name38']",
    LiveDealername39="[data-hook='live-casino-game-dealer-name39']",
    LiveDealername40="[data-hook='live-casino-game-dealer-name40']",
    LiveDealername41="[data-hook='live-casino-game-dealer-name41']",
    LiveDealername42="[data-hook='live-casino-game-dealer-name42']",
    LiveDealername43="[data-hook='live-casino-game-dealer-name43']",
    LiveDealername44="[data-hook='live-casino-game-dealer-name44']",
    LiveDealername45="[data-hook='live-casino-game-dealer-name45']",
    LiveDealername46="[data-hook='live-casino-game-dealer-name46']",
    LiveDealername47="[data-hook='live-casino-game-dealer-name47']",
    LiveDealername48="[data-hook='live-casino-game-dealer-name48']",
    LiveDealername49="[data-hook='live-casino-game-dealer-name49']",
    LiveDealername50="[data-hook='live-casino-game-dealer-name50']",

)

LiveblackjackPageMap = dict(
    LiveBlackjackGameimage1="[data-hook='live-casino-game-image1']",
    LiveBlackjackGameimage2="[data-hook='live-casino-game-image2']",
    LiveBlackjackGameimage3="[data-hook='live-casino-game-image3']",
    LiveBlackjackGameimage4="[data-hook='live-casino-game-image4']",
    LiveBlackjackGameimage5="[data-hook='live-casino-game-image5']",
    LiveBlackjackGameimage6="[data-hook='live-casino-game-image6']",
    LiveBlackjackGameimage7="[data-hook='live-casino-game-image7']",
    LiveBlackjackGameimage8="[data-hook='live-casino-game-image8']",
    LiveBlackjackGameimage9="[data-hook='live-casino-game-image9']",
    LiveBlackjackGameimage10="[data-hook='live-casino-game-image10']",
    LiveBlackjackGameimage11="[data-hook='live-casino-game-image11']",
    LiveBlackjackGameimage12="[data-hook='live-casino-game-image12']",
    LiveBlackjackGameimage13="[data-hook='live-casino-game-image13']",
    LiveBlackjackGameimage14="[data-hook='live-casino-game-image14']",
    LiveBlackjackGameimage15="[data-hook='live-casino-game-image15']",
    LiveBlackjackGameimage16="[data-hook='live-casino-game-image16']",
    LiveBlackjackGameimage17="[data-hook='live-casino-game-image17']",
    LiveBlackjackGameimage18="[data-hook='live-casino-game-image18']",
    LiveBlackjackGameimage19="[data-hook='live-casino-game-image19']",
    LiveBlackjackGameimage20="[data-hook='live-casino-game-image20']",
    LiveBlackjackGameimage21="[data-hook='live-casino-game-image21']",
    LiveBlackjackGameimage22="[data-hook='live-casino-game-image22']",
    LiveBlackjackGameimage23="[data-hook='live-casino-game-image23']",
    LiveBlackjackGameimage24="[data-hook='live-casino-game-image24']",
    LiveBlackjackGameimage25="[data-hook='live-casino-game-image25']",
    LiveBlackjackGameimage26="[data-hook='live-casino-game-image26']",
    LiveBlackjackGameimage27="[data-hook='live-casino-game-image27']",
    LiveBlackjackGameimage28="[data-hook='live-casino-game-image28']",
    LiveBlackjackGameimage29="[data-hook='live-casino-game-image29']",
    LiveBlackjackGameimage30="[data-hook='live-casino-game-image30']",
    LiveBlackjackGameimage31="[data-hook='live-casino-game-image31']",
    LiveBlackjackGameimage32="[data-hook='live-casino-game-image32']",
    LiveBlackjackGameimage33="[data-hook='live-casino-game-image33']",
    LiveBlackjackGameimage34="[data-hook='live-casino-game-image34']",
    LiveBlackjackGameimage35="[data-hook='live-casino-game-image35']",
    LiveBlackjackGameimage36="[data-hook='live-casino-game-image36']",
    LiveBlackjackGameimage37="[data-hook='live-casino-game-image37']",
    LiveBlackjackGameimage38="[data-hook='live-casino-game-image38']",
    LiveBlackjackGameimage39="[data-hook='live-casino-game-image39']",
    LiveBlackjackGameimage40="[data-hook='live-casino-game-image40']",
    LiveBlackjackGameimage41="[data-hook='live-casino-game-image41']",
    LiveBlackjackGameimage42="[data-hook='live-casino-game-image42']",
    LiveBlackjackGameimage43="[data-hook='live-casino-game-image43']",
    LiveBlackjackGameimage44="[data-hook='live-casino-game-image44']",
    LiveBlackjackGameimage45="[data-hook='live-casino-game-image45']",
    LiveBlackjackGameimage46="[data-hook='live-casino-game-image46']",
    LiveBlackjackGameimage47="[data-hook='live-casino-game-image47']",
    LiveBlackjackGameimage48="[data-hook='live-casino-game-image48']",
    LiveBlackjackGameimage49="[data-hook='live-casino-game-image49']",
    LiveBlackjackGameimage50="[data-hook='live-casino-game-image50']",

#live-casino-info-button1
Liveinfo1="[data-hook='live-casino-game-info-button1']",
    Liveinfo2="[data-hook='live-casino-game-info-button2']",
    Liveinfo3="[data-hook='live-casino-game-info-button3']",
    Liveinfo4="[data-hook='live-casino-game-info-button4']",
    Liveinfo5="[data-hook='live-casino-game-info-button5']",
    Liveinfo6="[data-hook='live-casino-game-info-button6']",
    Liveinfo7="[data-hook='live-casino-game-info-button7']",
    Liveinfo8="[data-hook='live-casino-game-info-button8']",
    Liveinfo9="[data-hook='live-casino-game-info-button9']",
    Liveinfo10="[data-hook='live-casino-game-info-button10']",
    Liveinfo11="[data-hook='live-casino-game-info-button11']",
    Liveinfo12="[data-hook='live-casino-game-info-button12']",
    Liveinfo13="[data-hook='live-casino-game-info-button13']",
    Liveinfo14="[data-hook='live-casino-game-info-button14']",
    Liveinfo15="[data-hook='live-casino-game-info-button15']",
    Liveinfo16="[data-hook='live-casino-game-info-button16']",
    Liveinfo17="[data-hook='live-casino-game-info-button17']",
    Liveinfo18="[data-hook='live-casino-game-info-button18']",
    Liveinfo19="[data-hook='live-casino-game-info-button19']",
    Liveinfo20="[data-hook='live-casino-game-info-button20']",
    Liveinfo21="[data-hook='live-casino-game-info-button21']",
    Liveinfo22="[data-hook='live-casino-game-info-button22']",
    Liveinfo23="[data-hook='live-casino-game-info-button23']",
    Liveinfo24="[data-hook='live-casino-game-info-button24']",
    Liveinfo25="[data-hook='live-casino-game-info-button25']",
    Liveinfo26="[data-hook='live-casino-game-info-button26']",
    Liveinfo27="[data-hook='live-casino-game-info-button27']",
    Liveinfo28="[data-hook='live-casino-game-info-button28']",
    Liveinfo29="[data-hook='live-casino-game-info-button29']",
    Liveinfo30="[data-hook='live-casino-game-info-button30']",
    Liveinfo31="[data-hook='live-casino-game-info-button31']",
    Liveinfo32="[data-hook='live-casino-game-info-button32']",
    Liveinfo33="[data-hook='live-casino-game-info-button33']",
    Liveinfo34="[data-hook='live-casino-game-info-button34']",
    Liveinfo35="[data-hook='live-casino-game-info-button35']",
    Liveinfo36="[data-hook='live-casino-game-info-button36']",
    Liveinfo37="[data-hook='live-casino-game-info-button37']",
    Liveinfo38="[data-hook='live-casino-game-info-button38']",
    Liveinfo39="[data-hook='live-casino-game-info-button39']",
    Liveinfo40="[data-hook='live-casino-game-info-button40']",
    Liveinfo41="[data-hook='live-casino-game-info-button41']",
    Liveinfo42="[data-hook='live-casino-game-info-button42']",
    Liveinfo43="[data-hook='live-casino-game-info-button43']",
    Liveinfo44="[data-hook='live-casino-game-info-button44']",
    Liveinfo45="[data-hook='live-casino-game-info-button45']",
    Liveinfo46="[data-hook='live-casino-game-info-button46']",
    Liveinfo47="[data-hook='live-casino-game-info-button47']",
    Liveinfo48="[data-hook='live-casino-game-info-button48']",
    Liveinfo49="[data-hook='live-casino-game-info-button49']",
    Liveinfo50="[data-hook='live-casino-game-info-button50']",

landingblackjack = "[data-hook='live-game-landing-page-breadcrumb-type']"
)
#Roulette game
LiveroulettePageMap = dict(
    LiveRouletteGameimage1="[data-hook='live-casino-game-image1']",
    LiveRouletteGameimage2="[data-hook='live-casino-game-image2']",
    LiveRouletteGameimage3="[data-hook='live-casino-game-image3']",
    LiveRouletteGameimage4="[data-hook='live-casino-game-image4']",
    LiveRouletteGameimage5="[data-hook='live-casino-game-image5']",
    LiveRouletteGameimage6="[data-hook='live-casino-game-image6']",
    LiveRouletteGameimage7="[data-hook='live-casino-game-image7']",
    LiveRouletteGameimage8="[data-hook='live-casino-game-image8']",
    LiveRouletteGameimage9="[data-hook='live-casino-game-image9']",
    LiveRouletteGameimage10="[data-hook='live-casino-game-image10']",
    LiveRouletteGameimage11="[data-hook='live-casino-game-image11']",
    LiveRouletteGameimage12="[data-hook='live-casino-game-image12']",
    LiveRouletteGameimage13="[data-hook='live-casino-game-image13']",
    LiveRouletteGameimage14="[data-hook='live-casino-game-image14']",
    LiveRouletteGameimage15="[data-hook='live-casino-game-image15']",
    LiveRouletteGameimage16="[data-hook='live-casino-game-image16']",
    LiveRouletteGameimage17="[data-hook='live-casino-game-image17']",
    LiveRouletteGameimage18="[data-hook='live-casino-game-image18']",
    LiveRouletteGameimage19="[data-hook='live-casino-game-image19']",
    LiveRouletteGameimage20="[data-hook='live-casino-game-image20']",
    LiveRouletteGameimage21="[data-hook='live-casino-game-image21']",
    LiveRouletteGameimage22="[data-hook='live-casino-game-image22']",
    LiveRouletteGameimage23="[data-hook='live-casino-game-image23']",
    LiveRouletteGameimage24="[data-hook='live-casino-game-image24']",
    LiveRouletteGameimage25="[data-hook='live-casino-game-image25']",
    LiveRouletteGameimage26="[data-hook='live-casino-game-image26']",
    LiveRouletteGameimage27="[data-hook='live-casino-game-image27']",
    LiveRouletteGameimage28="[data-hook='live-casino-game-image28']",
    LiveRouletteGameimage29="[data-hook='live-casino-game-image29']",
    LiveRouletteGameimage30="[data-hook='live-casino-game-image30']",
    LiveRouletteGameimage31="[data-hook='live-casino-game-image31']",
    LiveRouletteGameimage32="[data-hook='live-casino-game-image32']",
    LiveRouletteGameimage33="[data-hook='live-casino-game-image33']",
    LiveRouletteGameimage34="[data-hook='live-casino-game-image34']",
    LiveRouletteGameimage35="[data-hook='live-casino-game-image35']",
    LiveRouletteGameimage36="[data-hook='live-casino-game-image36']",
    LiveRouletteGameimage37="[data-hook='live-casino-game-image37']",
    LiveRouletteGameimage38="[data-hook='live-casino-game-image38']",
    LiveRouletteGameimage39="[data-hook='live-casino-game-image39']",
    LiveRouletteGameimage40="[data-hook='live-casino-game-image40']",
    LiveRouletteGameimage41="[data-hook='live-casino-game-image41']",
    LiveRouletteGameimage42="[data-hook='live-casino-game-image42']",
    LiveRouletteGameimage43="[data-hook='live-casino-game-image43']",
    LiveRouletteGameimage44="[data-hook='live-casino-game-image44']",
    LiveRouletteGameimage45="[data-hook='live-casino-game-image45']",
    LiveRouletteGameimage46="[data-hook='live-casino-game-image46']",
    LiveRouletteGameimage47="[data-hook='live-casino-game-image47']",
    LiveRouletteGameimage48="[data-hook='live-casino-game-image48']",
    LiveRouletteGameimage49="[data-hook='live-casino-game-image49']",
    LiveRouletteGameimage50="[data-hook='live-casino-game-image50']",


    # live-casino-info-button1
    Liveinfo1="[data-hook='live-casino-game-info-button1']",
    Liveinfo2="[data-hook='live-casino-game-info-button2']",
    Liveinfo3="[data-hook='live-casino-game-info-button3']",
    Liveinfo4="[data-hook='live-casino-game-info-button4']",
    Liveinfo5="[data-hook='live-casino-game-info-button5']",
    Liveinfo6="[data-hook='live-casino-game-info-button6']",
    Liveinfo7="[data-hook='live-casino-game-info-button7']",
    Liveinfo8="[data-hook='live-casino-game-info-button8']",
    Liveinfo9="[data-hook='live-casino-game-info-button9']",
    Liveinfo10="[data-hook='live-casino-game-info-button10']",
    Liveinfo11="[data-hook='live-casino-game-info-button11']",
    Liveinfo12="[data-hook='live-casino-game-info-button12']",
    Liveinfo13="[data-hook='live-casino-game-info-button13']",
    Liveinfo14="[data-hook='live-casino-game-info-button14']",
    Liveinfo15="[data-hook='live-casino-game-info-button15']",
    Liveinfo16="[data-hook='live-casino-game-info-button16']",
    Liveinfo17="[data-hook='live-casino-game-info-button17']",
    Liveinfo18="[data-hook='live-casino-game-info-button18']",
    Liveinfo19="[data-hook='live-casino-game-info-button19']",
    Liveinfo20="[data-hook='live-casino-game-info-button20']",
    Liveinfo21="[data-hook='live-casino-game-info-button21']",
    Liveinfo22="[data-hook='live-casino-game-info-button22']",
    Liveinfo23="[data-hook='live-casino-game-info-button23']",
    Liveinfo24="[data-hook='live-casino-game-info-button24']",
    Liveinfo25="[data-hook='live-casino-game-info-button25']",
    Liveinfo26="[data-hook='live-casino-game-info-button26']",
    Liveinfo27="[data-hook='live-casino-game-info-button27']",
    Liveinfo28="[data-hook='live-casino-game-info-button28']",
    Liveinfo29="[data-hook='live-casino-game-info-button29']",
    Liveinfo30="[data-hook='live-casino-game-info-button30']",
    Liveinfo31="[data-hook='live-casino-game-info-button31']",
    Liveinfo32="[data-hook='live-casino-game-info-button32']",
    Liveinfo33="[data-hook='live-casino-game-info-button33']",
    Liveinfo34="[data-hook='live-casino-game-info-button34']",
    Liveinfo35="[data-hook='live-casino-game-info-button35']",
    Liveinfo36="[data-hook='live-casino-game-info-button36']",
    Liveinfo37="[data-hook='live-casino-game-info-button37']",
    Liveinfo38="[data-hook='live-casino-game-info-button38']",
    Liveinfo39="[data-hook='live-casino-game-info-button39']",
    Liveinfo40="[data-hook='live-casino-game-info-button40']",
    Liveinfo41="[data-hook='live-casino-game-info-button41']",
    Liveinfo42="[data-hook='live-casino-game-info-button42']",
    Liveinfo43="[data-hook='live-casino-game-info-button43']",
    Liveinfo44="[data-hook='live-casino-game-info-button44']",
    Liveinfo45="[data-hook='live-casino-game-info-button45']",
    Liveinfo46="[data-hook='live-casino-game-info-button46']",
    Liveinfo47="[data-hook='live-casino-game-info-button47']",
    Liveinfo48="[data-hook='live-casino-game-info-button48']",
    Liveinfo49="[data-hook='live-casino-game-info-button49']",
    Liveinfo50="[data-hook='live-casino-game-info-button50']",
    landingroulette="[data-hook='live-game-landing-page-breadcrumb-type']",
    Livegamelaunch="[data-hook='live-game-launch-breadcrumb-name']",
    #live-casino-game-results1

)
LiveGameRoulettePastResults = dict(
Livegameresult1_1 = "[data-hook='1-live-casino-game-results1']",
Livegameresult2_1 = "[data-hook='1-live-casino-game-results2']",
Livegameresult3_1 = "[data-hook='1-live-casino-game-results3']",
Livegameresult4_1 = "[data-hook='1-live-casino-game-results4']",
Livegameresult5_1 = "[data-hook='1-live-casino-game-results5']",
Livegameresult6_1 = "[data-hook='1-live-casino-game-results6']",
Livegameresult7_1 = "[data-hook='1-live-casino-game-results7']",
Livegameresult8_1 = "[data-hook='1-live-casino-game-results8']",
Livegameresult9_1 = "[data-hook='1-live-casino-game-results9']",
Livegameresult10_1 = "[data-hook='1-live-casino-game-results10']",
Livegameresult11_1 = "[data-hook='1-live-casino-game-results11']",
Livegameresult12_1 = "[data-hook='1-live-casino-game-results12']",
Livegameresult13_1 = "[data-hook='1-live-casino-game-results13']",
Livegameresult14_1 = "[data-hook='1-live-casino-game-results14']",
Livegameresult15_1 = "[data-hook='1-live-casino-game-results15']",
Livegameresult16_1 = "[data-hook='1-live-casino-game-results16']",
Livegameresult17_1 = "[data-hook='1-live-casino-game-results17']",
Livegameresult18_1 = "[data-hook='1-live-casino-game-results18']",
Livegameresult19_1 = "[data-hook='1-live-casino-game-results19']",
Livegameresult20_1 = "[data-hook='1-live-casino-game-results20']",
Livegameresult21_1 = "[data-hook='1-live-casino-game-results21']",
Livegameresult22_1 = "[data-hook='1-live-casino-game-results22']",
Livegameresult23_1 = "[data-hook='1-live-casino-game-results23']",
Livegameresult24_1 = "[data-hook='1-live-casino-game-results24']",
Livegameresult25_1 = "[data-hook='1-live-casino-game-results25']",
Livegameresult26_1 = "[data-hook='1-live-casino-game-results26']",
Livegameresult27_1 = "[data-hook='1-live-casino-game-results27']",
Livegameresult28_1 = "[data-hook='1-live-casino-game-results28']",
Livegameresult29_1 = "[data-hook='1-live-casino-game-results29']",
Livegameresult30_1 = "[data-hook='1-live-casino-game-results30']",
Livegameresult31_1 = "[data-hook='1-live-casino-game-results31']",
Livegameresult32_1 = "[data-hook='1-live-casino-game-results32']",
Livegameresult33_1 = "[data-hook='1-live-casino-game-results33']",
Livegameresult34_1 = "[data-hook='1-live-casino-game-results34']",
Livegameresult35_1 = "[data-hook='1-live-casino-game-results35']",
Livegameresult36_1 = "[data-hook='1-live-casino-game-results36']",
Livegameresult37_1 = "[data-hook='1-live-casino-game-results37']",
Livegameresult38_1 = "[data-hook='1-live-casino-game-results38']",
Livegameresult39_1 = "[data-hook='1-live-casino-game-results39']",
Livegameresult40_1 = "[data-hook='1-live-casino-game-results40']",
Livegameresult41_1 = "[data-hook='1-live-casino-game-results41']",
Livegameresult42_1 = "[data-hook='1-live-casino-game-results42']",
Livegameresult43_1 = "[data-hook='1-live-casino-game-results43']",
Livegameresult44_1 = "[data-hook='1-live-casino-game-results44']",
Livegameresult45_1 = "[data-hook='1-live-casino-game-results45']",
Livegameresult46_1 = "[data-hook='1-live-casino-game-results46']",
Livegameresult47_1 = "[data-hook='1-live-casino-game-results47']",
Livegameresult48_1 = "[data-hook='1-live-casino-game-results48']",
Livegameresult49_1 = "[data-hook='1-live-casino-game-results49']",
Livegameresult50_1 = "[data-hook='1-live-casino-game-results50']",


Livegameresult1_2 = "[data-hook='2-live-casino-game-results1']",
Livegameresult2_2 = "[data-hook='2-live-casino-game-results2']",
Livegameresult3_2 = "[data-hook='2-live-casino-game-results3']",
Livegameresult4_2 = "[data-hook='2-live-casino-game-results4']",
Livegameresult5_2 = "[data-hook='2-live-casino-game-results5']",
Livegameresult6_2 = "[data-hook='2-live-casino-game-results6']",
Livegameresult7_2 = "[data-hook='2-live-casino-game-results7']",
Livegameresult8_2 = "[data-hook='2-live-casino-game-results8']",
Livegameresult9_2 = "[data-hook='2-live-casino-game-results9']",
Livegameresult10_2 = "[data-hook='2-live-casino-game-results10']",
Livegameresult11_2 = "[data-hook='2-live-casino-game-results11']",
Livegameresult12_2 = "[data-hook='2-live-casino-game-results12']",
Livegameresult13_2 = "[data-hook='2-live-casino-game-results13']",
Livegameresult14_2 = "[data-hook='2-live-casino-game-results14']",
Livegameresult15_2 = "[data-hook='2-live-casino-game-results15']",
Livegameresult16_2 = "[data-hook='2-live-casino-game-results16']",
Livegameresult17_2 = "[data-hook='2-live-casino-game-results17']",
Livegameresult18_2 = "[data-hook='2-live-casino-game-results18']",
Livegameresult19_2 = "[data-hook='2-live-casino-game-results19']",
Livegameresult20_2 = "[data-hook='2-live-casino-game-results20']",
Livegameresult21_2 = "[data-hook='2-live-casino-game-results21']",
Livegameresult22_2 = "[data-hook='2-live-casino-game-results22']",
Livegameresult23_2 = "[data-hook='2-live-casino-game-results23']",
Livegameresult24_2 = "[data-hook='2-live-casino-game-results24']",
Livegameresult25_2 = "[data-hook='2-live-casino-game-results25']",
Livegameresult26_2 = "[data-hook='2-live-casino-game-results26']",
Livegameresult27_2 = "[data-hook='2-live-casino-game-results27']",
Livegameresult28_2 = "[data-hook='2-live-casino-game-results28']",
Livegameresult29_2 = "[data-hook='2-live-casino-game-results29']",
Livegameresult30_2 = "[data-hook='2-live-casino-game-results30']",
Livegameresult31_2 = "[data-hook='2-live-casino-game-results31']",
Livegameresult32_2 = "[data-hook='2-live-casino-game-results32']",
Livegameresult33_2 = "[data-hook='2-live-casino-game-results33']",
Livegameresult34_2 = "[data-hook='2-live-casino-game-results34']",
Livegameresult35_2 = "[data-hook='2-live-casino-game-results35']",
Livegameresult36_2 = "[data-hook='2-live-casino-game-results36']",
Livegameresult37_2 = "[data-hook='2-live-casino-game-results37']",
Livegameresult38_2 = "[data-hook='2-live-casino-game-results38']",
Livegameresult39_2 = "[data-hook='2-live-casino-game-results39']",
Livegameresult40_2 = "[data-hook='2-live-casino-game-results40']",
Livegameresult41_2 = "[data-hook='2-live-casino-game-results41']",
Livegameresult42_2 = "[data-hook='2-live-casino-game-results42']",
Livegameresult43_2 = "[data-hook='2-live-casino-game-results43']",
Livegameresult44_2 = "[data-hook='2-live-casino-game-results44']",
Livegameresult45_2 = "[data-hook='2-live-casino-game-results45']",
Livegameresult46_2 = "[data-hook='2-live-casino-game-results46']",
Livegameresult47_2 = "[data-hook='2-live-casino-game-results47']",
Livegameresult48_2 = "[data-hook='2-live-casino-game-results48']",
Livegameresult49_2 = "[data-hook='2-live-casino-game-results49']",
Livegameresult50_2 = "[data-hook='2-live-casino-game-results50']",


Livegameresult1_3 = "[data-hook='3-live-casino-game-results1']",
Livegameresult2_3 = "[data-hook='3-live-casino-game-results2']",
Livegameresult3_3 = "[data-hook='3-live-casino-game-results3']",
Livegameresult4_3 = "[data-hook='3-live-casino-game-results4']",
Livegameresult5_3 = "[data-hook='3-live-casino-game-results5']",
Livegameresult6_3 = "[data-hook='3-live-casino-game-results6']",
Livegameresult7_3 = "[data-hook='3-live-casino-game-results7']",
Livegameresult8_3 = "[data-hook='3-live-casino-game-results8']",
Livegameresult9_3 = "[data-hook='3-live-casino-game-results9']",
Livegameresult10_3 = "[data-hook='3-live-casino-game-results10']",
Livegameresult11_3 = "[data-hook='3-live-casino-game-results11']",
Livegameresult12_3 = "[data-hook='3-live-casino-game-results12']",
Livegameresult13_3 = "[data-hook='3-live-casino-game-results13']",
Livegameresult14_3 = "[data-hook='3-live-casino-game-results14']",
Livegameresult15_3 = "[data-hook='3-live-casino-game-results15']",
Livegameresult16_3 = "[data-hook='3-live-casino-game-results16']",
Livegameresult17_3 = "[data-hook='3-live-casino-game-results17']",
Livegameresult18_3 = "[data-hook='3-live-casino-game-results18']",
Livegameresult19_3 = "[data-hook='3-live-casino-game-results19']",
Livegameresult20_3 = "[data-hook='3-live-casino-game-results20']",
Livegameresult21_3 = "[data-hook='3-live-casino-game-results21']",
Livegameresult22_3 = "[data-hook='3-live-casino-game-results22']",
Livegameresult23_3 = "[data-hook='3-live-casino-game-results23']",
Livegameresult24_3 = "[data-hook='3-live-casino-game-results24']",
Livegameresult25_3 = "[data-hook='3-live-casino-game-results25']",
Livegameresult26_3 = "[data-hook='3-live-casino-game-results26']",
Livegameresult27_3 = "[data-hook='3-live-casino-game-results27']",
Livegameresult28_3 = "[data-hook='3-live-casino-game-results28']",
Livegameresult29_3 = "[data-hook='3-live-casino-game-results29']",
Livegameresult30_3 = "[data-hook='3-live-casino-game-results30']",
Livegameresult31_3 = "[data-hook='3-live-casino-game-results31']",
Livegameresult32_3 = "[data-hook='3-live-casino-game-results32']",
Livegameresult33_3 = "[data-hook='3-live-casino-game-results33']",
Livegameresult34_3 = "[data-hook='3-live-casino-game-results34']",
Livegameresult35_3 = "[data-hook='3-live-casino-game-results35']",
Livegameresult36_3 = "[data-hook='3-live-casino-game-results36']",
Livegameresult37_3 = "[data-hook='3-live-casino-game-results37']",
Livegameresult38_3 = "[data-hook='3-live-casino-game-results38']",
Livegameresult39_3 = "[data-hook='3-live-casino-game-results39']",
Livegameresult40_3 = "[data-hook='3-live-casino-game-results40']",
Livegameresult41_3 = "[data-hook='3-live-casino-game-results41']",
Livegameresult42_3 = "[data-hook='3-live-casino-game-results42']",
Livegameresult43_3 = "[data-hook='3-live-casino-game-results43']",
Livegameresult44_3 = "[data-hook='3-live-casino-game-results44']",
Livegameresult45_3 = "[data-hook='3-live-casino-game-results45']",
Livegameresult46_3 = "[data-hook='3-live-casino-game-results46']",
Livegameresult47_3 = "[data-hook='3-live-casino-game-results47']",
Livegameresult48_3 = "[data-hook='3-live-casino-game-results48']",
Livegameresult49_3 = "[data-hook='3-live-casino-game-results49']",
Livegameresult50_3 = "[data-hook='3-live-casino-game-results50']",


Livegameresult1_4 = "[data-hook='4-live-casino-game-results1']",
Livegameresult2_4 = "[data-hook='4-live-casino-game-results2']",
Livegameresult3_4 = "[data-hook='4-live-casino-game-results3']",
Livegameresult4_4 = "[data-hook='4-live-casino-game-results4']",
Livegameresult5_4 = "[data-hook='4-live-casino-game-results5']",
Livegameresult6_4 = "[data-hook='4-live-casino-game-results6']",
Livegameresult7_4 = "[data-hook='4-live-casino-game-results7']",
Livegameresult8_4 = "[data-hook='4-live-casino-game-results8']",
Livegameresult9_4 = "[data-hook='4-live-casino-game-results9']",
Livegameresult10_4 = "[data-hook='4-live-casino-game-results10']",
Livegameresult11_4 = "[data-hook='4-live-casino-game-results11']",
Livegameresult12_4 = "[data-hook='4-live-casino-game-results12']",
Livegameresult13_4 = "[data-hook='4-live-casino-game-results13']",
Livegameresult14_4 = "[data-hook='4-live-casino-game-results14']",
Livegameresult15_4 = "[data-hook='4-live-casino-game-results15']",
Livegameresult16_4 = "[data-hook='4-live-casino-game-results16']",
Livegameresult17_4 = "[data-hook='4-live-casino-game-results17']",
Livegameresult18_4 = "[data-hook='4-live-casino-game-results18']",
Livegameresult19_4 = "[data-hook='4-live-casino-game-results19']",
Livegameresult20_4 = "[data-hook='4-live-casino-game-results20']",
Livegameresult21_4 = "[data-hook='4-live-casino-game-results21']",
Livegameresult22_4 = "[data-hook='4-live-casino-game-results22']",
Livegameresult23_4 = "[data-hook='4-live-casino-game-results23']",
Livegameresult24_4 = "[data-hook='4-live-casino-game-results24']",
Livegameresult25_4 = "[data-hook='4-live-casino-game-results25']",
Livegameresult26_4 = "[data-hook='4-live-casino-game-results26']",
Livegameresult27_4 = "[data-hook='4-live-casino-game-results27']",
Livegameresult28_4 = "[data-hook='4-live-casino-game-results28']",
Livegameresult29_4 = "[data-hook='4-live-casino-game-results29']",
Livegameresult30_4 = "[data-hook='4-live-casino-game-results30']",
Livegameresult31_4 = "[data-hook='4-live-casino-game-results31']",
Livegameresult32_4 = "[data-hook='4-live-casino-game-results32']",
Livegameresult33_4 = "[data-hook='4-live-casino-game-results33']",
Livegameresult34_4 = "[data-hook='4-live-casino-game-results34']",
Livegameresult35_4 = "[data-hook='4-live-casino-game-results35']",
Livegameresult36_4 = "[data-hook='4-live-casino-game-results36']",
Livegameresult37_4 = "[data-hook='4-live-casino-game-results37']",
Livegameresult38_4 = "[data-hook='4-live-casino-game-results38']",
Livegameresult39_4 = "[data-hook='4-live-casino-game-results39']",
Livegameresult40_4 = "[data-hook='4-live-casino-game-results40']",
Livegameresult41_4 = "[data-hook='4-live-casino-game-results41']",
Livegameresult42_4 = "[data-hook='4-live-casino-game-results42']",
Livegameresult43_4 = "[data-hook='4-live-casino-game-results43']",
Livegameresult44_4 = "[data-hook='4-live-casino-game-results44']",
Livegameresult45_4 = "[data-hook='4-live-casino-game-results45']",
Livegameresult46_4 = "[data-hook='4-live-casino-game-results46']",
Livegameresult47_4 = "[data-hook='4-live-casino-game-results47']",
Livegameresult48_4 = "[data-hook='4-live-casino-game-results48']",
Livegameresult49_4 = "[data-hook='4-live-casino-game-results49']",
Livegameresult50_4 = "[data-hook='4-live-casino-game-results50']",


Livegameresult1_5 = "[data-hook='5-live-casino-game-results1']",
Livegameresult2_5 = "[data-hook='5-live-casino-game-results2']",
Livegameresult3_5 = "[data-hook='5-live-casino-game-results3']",
Livegameresult4_5 = "[data-hook='5-live-casino-game-results4']",
Livegameresult5_5 = "[data-hook='5-live-casino-game-results5']",
Livegameresult6_5 = "[data-hook='5-live-casino-game-results6']",
Livegameresult7_5 = "[data-hook='5-live-casino-game-results7']",
Livegameresult8_5 = "[data-hook='5-live-casino-game-results8']",
Livegameresult9_5 = "[data-hook='5-live-casino-game-results9']",
Livegameresult10_5 = "[data-hook='5-live-casino-game-results10']",
Livegameresult11_5 = "[data-hook='5-live-casino-game-results11']",
Livegameresult12_5 = "[data-hook='5-live-casino-game-results12']",
Livegameresult13_5 = "[data-hook='5-live-casino-game-results13']",
Livegameresult14_5 = "[data-hook='5-live-casino-game-results14']",
Livegameresult15_5 = "[data-hook='5-live-casino-game-results15']",
Livegameresult16_5 = "[data-hook='5-live-casino-game-results16']",
Livegameresult17_5 = "[data-hook='5-live-casino-game-results17']",
Livegameresult18_5 = "[data-hook='5-live-casino-game-results18']",
Livegameresult19_5 = "[data-hook='5-live-casino-game-results19']",
Livegameresult20_5 = "[data-hook='5-live-casino-game-results20']",
Livegameresult21_5 = "[data-hook='5-live-casino-game-results21']",
Livegameresult22_5 = "[data-hook='5-live-casino-game-results22']",
Livegameresult23_5 = "[data-hook='5-live-casino-game-results23']",
Livegameresult24_5 = "[data-hook='5-live-casino-game-results24']",
Livegameresult25_5 = "[data-hook='5-live-casino-game-results25']",
Livegameresult26_5 = "[data-hook='5-live-casino-game-results26']",
Livegameresult27_5 = "[data-hook='5-live-casino-game-results27']",
Livegameresult28_5 = "[data-hook='5-live-casino-game-results28']",
Livegameresult29_5 = "[data-hook='5-live-casino-game-results29']",
Livegameresult30_5 = "[data-hook='5-live-casino-game-results30']",
Livegameresult31_5 = "[data-hook='5-live-casino-game-results31']",
Livegameresult32_5 = "[data-hook='5-live-casino-game-results32']",
Livegameresult33_5 = "[data-hook='5-live-casino-game-results33']",
Livegameresult34_5 = "[data-hook='5-live-casino-game-results34']",
Livegameresult35_5 = "[data-hook='5-live-casino-game-results35']",
Livegameresult36_5 = "[data-hook='5-live-casino-game-results36']",
Livegameresult37_5 = "[data-hook='5-live-casino-game-results37']",
Livegameresult38_5 = "[data-hook='5-live-casino-game-results38']",
Livegameresult39_5 = "[data-hook='5-live-casino-game-results39']",
Livegameresult40_5 = "[data-hook='5-live-casino-game-results40']",
Livegameresult41_5 = "[data-hook='5-live-casino-game-results41']",
Livegameresult42_5 = "[data-hook='5-live-casino-game-results42']",
Livegameresult43_5 = "[data-hook='5-live-casino-game-results43']",
Livegameresult44_5 = "[data-hook='5-live-casino-game-results44']",
Livegameresult45_5 = "[data-hook='5-live-casino-game-results45']",
Livegameresult46_5 = "[data-hook='5-live-casino-game-results46']",
Livegameresult47_5 = "[data-hook='5-live-casino-game-results47']",
Livegameresult48_5 = "[data-hook='5-live-casino-game-results48']",
Livegameresult49_5 = "[data-hook='5-live-casino-game-results49']",
Livegameresult50_5 = "[data-hook='5-live-casino-game-results50']",

)
Livegamescommon = dict(
    Livegamereult1="[data-hook='live-casino-game-results1']",
    Livegamereult2="[data-hook='live-casino-game-results2']",
    Livegamereult3="[data-hook='live-casino-game-results3']",
    Livegamereult4="[data-hook='live-casino-game-results4']",
    Livegamereult5="[data-hook='live-casino-game-results5']",
    Livegamereult6="[data-hook='live-casino-game-results6']",
    Livegamereult7="[data-hook='live-casino-game-results7']",
    Livegamereult8="[data-hook='live-casino-game-results8']",
    Livegamereult9="[data-hook='live-casino-game-results9']",
    Livegamereult10="[data-hook='live-casino-game-results10']",
    Livegamereult11="[data-hook='live-casino-game-results11']",
    Livegamereult12="[data-hook='live-casino-game-results12']",
    Livegamereult13="[data-hook='live-casino-game-results13']",
    Livegamereult14="[data-hook='live-casino-game-results14']",
    Livegamereult15="[data-hook='live-casino-game-results15']",
    Livegamereult16="[data-hook='live-casino-game-results16']",
    Livegamereult17="[data-hook='live-casino-game-results17']",
    Livegamereult18="[data-hook='live-casino-game-results18']",
    Livegamereult19="[data-hook='live-casino-game-results19']",
    Livegamereult20="[data-hook='live-casino-game-results20']",
    Livegamereult21="[data-hook='live-casino-game-results21']",
    Livegamereult22="[data-hook='live-casino-game-results22']",
    Livegamereult23="[data-hook='live-casino-game-results23']",
    Livegamereult24="[data-hook='live-casino-game-results24']",
    Livegamereult25="[data-hook='live-casino-game-results25']",
    Livegamereult26="[data-hook='live-casino-game-results26']",
    Livegamereult27="[data-hook='live-casino-game-results27']",
    Livegamereult28="[data-hook='live-casino-game-results28']",
    Livegamereult29="[data-hook='live-casino-game-results29']",
    Livegamereult30="[data-hook='live-casino-game-results30']",
    Livegamereult31="[data-hook='live-casino-game-results31']",
    Livegamereult32="[data-hook='live-casino-game-results32']",
    Livegamereult33="[data-hook='live-casino-game-results33']",
    Livegamereult34="[data-hook='live-casino-game-results34']",
    Livegamereult35="[data-hook='live-casino-game-results35']",
    Livegamereult36="[data-hook='live-casino-game-results36']",
    Livegamereult37="[data-hook='live-casino-game-results37']",
    Livegamereult38="[data-hook='live-casino-game-results38']",
    Livegamereult39="[data-hook='live-casino-game-results39']",
    Livegamereult40="[data-hook='live-casino-game-results40']",
    Livegamereult41="[data-hook='live-casino-game-results41']",
    Livegamereult42="[data-hook='live-casino-game-results42']",
    Livegamereult43="[data-hook='live-casino-game-results43']",
    Livegamereult44="[data-hook='live-casino-game-results44']",
    Livegamereult45="[data-hook='live-casino-game-results45']",
    Livegamereult46="[data-hook='live-casino-game-results46']",
    Livegamereult47="[data-hook='live-casino-game-results47']",
    Livegamereult48="[data-hook='live-casino-game-results48']",
    Livegamereult49="[data-hook='live-casino-game-results49']",
    Livegamereult50="[data-hook='live-casino-game-results50']",

)

LivebaccaratPageMap = dict(
    LiveBaccaratgameimage1="[data-hook='live-casino-game-image1']",
    LiveBaccaratgameimage2="[data-hook='live-casino-game-image2']",
    LiveBaccaratgameimage3="[data-hook='live-casino-game-image3']",
    LiveBaccaratgameimage4="[data-hook='live-casino-game-image4']",
    LiveBaccaratgameimage5="[data-hook='live-casino-game-image5']",
    LiveBaccaratgameimage6="[data-hook='live-casino-game-image6']",
    LiveBaccaratgameimage7="[data-hook='live-casino-game-image7']",
    LiveBaccaratgameimage8="[data-hook='live-casino-game-image8']",
    LiveBaccaratgameimage9="[data-hook='live-casino-game-image9']",
    LiveBaccaratgameimage10="[data-hook='live-casino-game-image10']",
    LiveBaccaratgameimage11="[data-hook='live-casino-game-image11']",
    LiveBaccaratgameimage12="[data-hook='live-casino-game-image12']",
    LiveBaccaratgameimage13="[data-hook='live-casino-game-image13']",
    LiveBaccaratgameimage14="[data-hook='live-casino-game-image14']",
    LiveBaccaratgameimage15="[data-hook='live-casino-game-image15']",
    LiveBaccaratgameimage16="[data-hook='live-casino-game-image16']",
    LiveBaccaratgameimage17="[data-hook='live-casino-game-image17']",
    LiveBaccaratgameimage18="[data-hook='live-casino-game-image18']",
    LiveBaccaratgameimage19="[data-hook='live-casino-game-image19']",
    LiveBaccaratgameimage20="[data-hook='live-casino-game-image20']",
    LiveBaccaratgameimage21="[data-hook='live-casino-game-image21']",
    LiveBaccaratgameimage22="[data-hook='live-casino-game-image22']",
    LiveBaccaratgameimage23="[data-hook='live-casino-game-image23']",
    LiveBaccaratgameimage24="[data-hook='live-casino-game-image24']",
    LiveBaccaratgameimage25="[data-hook='live-casino-game-image25']",
    LiveBaccaratgameimage26="[data-hook='live-casino-game-image26']",
    LiveBaccaratgameimage27="[data-hook='live-casino-game-image27']",
    LiveBaccaratgameimage28="[data-hook='live-casino-game-image28']",
    LiveBaccaratgameimage29="[data-hook='live-casino-game-image29']",
    LiveBaccaratgameimage30="[data-hook='live-casino-game-image30']",
    LiveBaccaratgameimage31="[data-hook='live-casino-game-image31']",
    LiveBaccaratgameimage32="[data-hook='live-casino-game-image32']",
    LiveBaccaratgameimage33="[data-hook='live-casino-game-image33']",
    LiveBaccaratgameimage34="[data-hook='live-casino-game-image34']",
    LiveBaccaratgameimage35="[data-hook='live-casino-game-image35']",
    LiveBaccaratgameimage36="[data-hook='live-casino-game-image36']",
    LiveBaccaratgameimage37="[data-hook='live-casino-game-image37']",
    LiveBaccaratgameimage38="[data-hook='live-casino-game-image38']",
    LiveBaccaratgameimage39="[data-hook='live-casino-game-image39']",
    LiveBaccaratgameimage40="[data-hook='live-casino-game-image40']",
    LiveBaccaratgameimage41="[data-hook='live-casino-game-image41']",
    LiveBaccaratgameimage42="[data-hook='live-casino-game-image42']",
    LiveBaccaratgameimage43="[data-hook='live-casino-game-image43']",
    LiveBaccaratgameimage44="[data-hook='live-casino-game-image44']",
    LiveBaccaratgameimage45="[data-hook='live-casino-game-image45']",
    LiveBaccaratgameimage46="[data-hook='live-casino-game-image46']",
    LiveBaccaratgameimage47="[data-hook='live-casino-game-image47']",
    LiveBaccaratgameimage48="[data-hook='live-casino-game-image48']",
    LiveBaccaratgameimage49="[data-hook='live-casino-game-image49']",
    LiveBaccaratgameimage50="[data-hook='live-casino-game-image50']",

    #live-casino-info-button1
Liveinfo1="[data-hook='live-casino-game-info-button1']",
    Liveinfo2="[data-hook='live-casino-game-info-button2']",
    Liveinfo3="[data-hook='live-casino-game-info-button3']",
    Liveinfo4="[data-hook='live-casino-game-info-button4']",
    Liveinfo5="[data-hook='live-casino-game-info-button5']",
    Liveinfo6="[data-hook='live-casino-game-info-button6']",
    Liveinfo7="[data-hook='live-casino-game-info-button7']",
    Liveinfo8="[data-hook='live-casino-game-info-button8']",
    Liveinfo9="[data-hook='live-casino-game-info-button9']",
    Liveinfo10="[data-hook='live-casino-game-info-button10']",
    Liveinfo11="[data-hook='live-casino-game-info-button11']",
    Liveinfo12="[data-hook='live-casino-game-info-button12']",
    Liveinfo13="[data-hook='live-casino-game-info-button13']",
    Liveinfo14="[data-hook='live-casino-game-info-button14']",
    Liveinfo15="[data-hook='live-casino-game-info-button15']",
    Liveinfo16="[data-hook='live-casino-game-info-button16']",
    Liveinfo17="[data-hook='live-casino-game-info-button17']",
    Liveinfo18="[data-hook='live-casino-game-info-button18']",
    Liveinfo19="[data-hook='live-casino-game-info-button19']",
    Liveinfo20="[data-hook='live-casino-game-info-button20']",
    Liveinfo21="[data-hook='live-casino-game-info-button21']",
    Liveinfo22="[data-hook='live-casino-game-info-button22']",
    Liveinfo23="[data-hook='live-casino-game-info-button23']",
    Liveinfo24="[data-hook='live-casino-game-info-button24']",
    Liveinfo25="[data-hook='live-casino-game-info-button25']",
    Liveinfo26="[data-hook='live-casino-game-info-button26']",
    Liveinfo27="[data-hook='live-casino-game-info-button27']",
    Liveinfo28="[data-hook='live-casino-game-info-button28']",
    Liveinfo29="[data-hook='live-casino-game-info-button29']",
    Liveinfo30="[data-hook='live-casino-game-info-button30']",
    Liveinfo31="[data-hook='live-casino-game-info-button31']",
    Liveinfo32="[data-hook='live-casino-game-info-button32']",
    Liveinfo33="[data-hook='live-casino-game-info-button33']",
    Liveinfo34="[data-hook='live-casino-game-info-button34']",
    Liveinfo35="[data-hook='live-casino-game-info-button35']",
    Liveinfo36="[data-hook='live-casino-game-info-button36']",
    Liveinfo37="[data-hook='live-casino-game-info-button37']",
    Liveinfo38="[data-hook='live-casino-game-info-button38']",
    Liveinfo39="[data-hook='live-casino-game-info-button39']",
    Liveinfo40="[data-hook='live-casino-game-info-button40']",
    Liveinfo41="[data-hook='live-casino-game-info-button41']",
    Liveinfo42="[data-hook='live-casino-game-info-button42']",
    Liveinfo43="[data-hook='live-casino-game-info-button43']",
    Liveinfo44="[data-hook='live-casino-game-info-button44']",
    Liveinfo45="[data-hook='live-casino-game-info-button45']",
    Liveinfo46="[data-hook='live-casino-game-info-button46']",
    Liveinfo47="[data-hook='live-casino-game-info-button47']",
    Liveinfo48="[data-hook='live-casino-game-info-button48']",
    Liveinfo49="[data-hook='live-casino-game-info-button49']",
    Liveinfo50="[data-hook='live-casino-game-info-button50']",

landingbaccarat = "[data-hook='live-game-landing-page-breadcrumb-type']"

)
LivepokerPageMap = dict(
    LivePokerGameimage1="[data-hook='live-casino-game-image1']",
    LivePokerGameimage2="[data-hook='live-casino-game-image2']",
    LivePokerGameimage3="[data-hook='live-casino-game-image3']",
    LivePokerGameimage4="[data-hook='live-casino-game-image4']",
    LivePokerGameimage5="[data-hook='live-casino-game-image5']",
    LivePokerGameimage6="[data-hook='live-casino-game-image6']",
    LivePokerGameimage7="[data-hook='live-casino-game-image7']",
    LivePokerGameimage8="[data-hook='live-casino-game-image8']",
    LivePokerGameimage9="[data-hook='live-casino-game-image9']",
    LivePokerGameimage10="[data-hook='live-casino-game-image10']",
    LivePokerGameimage11="[data-hook='live-casino-game-image11']",
    LivePokerGameimage12="[data-hook='live-casino-game-image12']",
    LivePokerGameimage13="[data-hook='live-casino-game-image13']",
    LivePokerGameimage14="[data-hook='live-casino-game-image14']",
    LivePokerGameimage15="[data-hook='live-casino-game-image15']",
    LivePokerGameimage16="[data-hook='live-casino-game-image16']",
    LivePokerGameimage17="[data-hook='live-casino-game-image17']",
    LivePokerGameimage18="[data-hook='live-casino-game-image18']",
    LivePokerGameimage19="[data-hook='live-casino-game-image19']",
    LivePokerGameimage20="[data-hook='live-casino-game-image20']",
    LivePokerGameimage21="[data-hook='live-casino-game-image21']",
    LivePokerGameimage22="[data-hook='live-casino-game-image22']",
    LivePokerGameimage23="[data-hook='live-casino-game-image23']",
    LivePokerGameimage24="[data-hook='live-casino-game-image24']",
    LivePokerGameimage25="[data-hook='live-casino-game-image25']",
    LivePokerGameimage26="[data-hook='live-casino-game-image26']",
    LivePokerGameimage27="[data-hook='live-casino-game-image27']",
    LivePokerGameimage28="[data-hook='live-casino-game-image28']",
    LivePokerGameimage29="[data-hook='live-casino-game-image29']",
    LivePokerGameimage30="[data-hook='live-casino-game-image30']",
    LivePokerGameimage31="[data-hook='live-casino-game-image31']",
    LivePokerGameimage32="[data-hook='live-casino-game-image32']",
    LivePokerGameimage33="[data-hook='live-casino-game-image33']",
    LivePokerGameimage34="[data-hook='live-casino-game-image34']",
    LivePokerGameimage35="[data-hook='live-casino-game-image35']",
    LivePokerGameimage36="[data-hook='live-casino-game-image36']",
    LivePokerGameimage37="[data-hook='live-casino-game-image37']",
    LivePokerGameimage38="[data-hook='live-casino-game-image38']",
    LivePokerGameimage39="[data-hook='live-casino-game-image39']",
    LivePokerGameimage40="[data-hook='live-casino-game-image40']",
    LivePokerGameimage41="[data-hook='live-casino-game-image41']",
    LivePokerGameimage42="[data-hook='live-casino-game-image42']",
    LivePokerGameimage43="[data-hook='live-casino-game-image43']",
    LivePokerGameimage44="[data-hook='live-casino-game-image44']",
    LivePokerGameimage45="[data-hook='live-casino-game-image45']",
    LivePokerGameimage46="[data-hook='live-casino-game-image46']",
    LivePokerGameimage47="[data-hook='live-casino-game-image47']",
    LivePokerGameimage48="[data-hook='live-casino-game-image48']",
    LivePokerGameimage49="[data-hook='live-casino-game-image49']",
    LivePokerGameimage50="[data-hook='live-casino-game-image50']",

    # live-casino-info-button1
    Liveinfo1="[data-hook='live-casino-game-info-button1']",
    Liveinfo2="[data-hook='live-casino-game-info-button2']",
    Liveinfo3="[data-hook='live-casino-game-info-button3']",
    Liveinfo4="[data-hook='live-casino-game-info-button4']",
    Liveinfo5="[data-hook='live-casino-game-info-button5']",
    Liveinfo6="[data-hook='live-casino-game-info-button6']",
    Liveinfo7="[data-hook='live-casino-game-info-button7']",
    Liveinfo8="[data-hook='live-casino-game-info-button8']",
    Liveinfo9="[data-hook='live-casino-game-info-button9']",
    Liveinfo10="[data-hook='live-casino-game-info-button10']",
    Liveinfo11="[data-hook='live-casino-game-info-button11']",
    Liveinfo12="[data-hook='live-casino-game-info-button12']",
    Liveinfo13="[data-hook='live-casino-game-info-button13']",
    Liveinfo14="[data-hook='live-casino-game-info-button14']",
    Liveinfo15="[data-hook='live-casino-game-info-button15']",
    Liveinfo16="[data-hook='live-casino-game-info-button16']",
    Liveinfo17="[data-hook='live-casino-game-info-button17']",
    Liveinfo18="[data-hook='live-casino-game-info-button18']",
    Liveinfo19="[data-hook='live-casino-game-info-button19']",
    Liveinfo20="[data-hook='live-casino-game-info-button20']",
    Liveinfo21="[data-hook='live-casino-game-info-button21']",
    Liveinfo22="[data-hook='live-casino-game-info-button22']",
    Liveinfo23="[data-hook='live-casino-game-info-button23']",
    Liveinfo24="[data-hook='live-casino-game-info-button24']",
    Liveinfo25="[data-hook='live-casino-game-info-button25']",
    Liveinfo26="[data-hook='live-casino-game-info-button26']",
    Liveinfo27="[data-hook='live-casino-game-info-button27']",
    Liveinfo28="[data-hook='live-casino-game-info-button28']",
    Liveinfo29="[data-hook='live-casino-game-info-button29']",
    Liveinfo30="[data-hook='live-casino-game-info-button30']",
    Liveinfo31="[data-hook='live-casino-game-info-button31']",
    Liveinfo32="[data-hook='live-casino-game-info-button32']",
    Liveinfo33="[data-hook='live-casino-game-info-button33']",
    Liveinfo34="[data-hook='live-casino-game-info-button34']",
    Liveinfo35="[data-hook='live-casino-game-info-button35']",
    Liveinfo36="[data-hook='live-casino-game-info-button36']",
    Liveinfo37="[data-hook='live-casino-game-info-button37']",
    Liveinfo38="[data-hook='live-casino-game-info-button38']",
    Liveinfo39="[data-hook='live-casino-game-info-button39']",
    Liveinfo40="[data-hook='live-casino-game-info-button40']",
    Liveinfo41="[data-hook='live-casino-game-info-button41']",
    Liveinfo42="[data-hook='live-casino-game-info-button42']",
    Liveinfo43="[data-hook='live-casino-game-info-button43']",
    Liveinfo44="[data-hook='live-casino-game-info-button44']",
    Liveinfo45="[data-hook='live-casino-game-info-button45']",
    Liveinfo46="[data-hook='live-casino-game-info-button46']",
    Liveinfo47="[data-hook='live-casino-game-info-button47']",
    Liveinfo48="[data-hook='live-casino-game-info-button48']",
    Liveinfo49="[data-hook='live-casino-game-info-button49']",
    Liveinfo50="[data-hook='live-casino-game-info-button50']",

    landingpoker="[data-hook='live-game-landing-page-breadcrumb-type']"

)

LiveOthersPageMap = dict(
    LiveOthersGameimage1="[data-hook='live-casino-game-image1']",
    LiveOthersGameimage2="[data-hook='live-casino-game-image2']",
    LiveOthersGameimage3="[data-hook='live-casino-game-image3']",
    LiveOthersGameimage4="[data-hook='live-casino-game-image4']",
    LiveOthersGameimage5="[data-hook='live-casino-game-image5']",
    LiveOthersGameimage6="[data-hook='live-casino-game-image6']",
    LiveOthersGameimage7="[data-hook='live-casino-game-image7']",
    LiveOthersGameimage8="[data-hook='live-casino-game-image8']",
    LiveOthersGameimage9="[data-hook='live-casino-game-image9']",
    LiveOthersGameimage10="[data-hook='live-casino-game-image10']",
    LiveOthersGameimage11="[data-hook='live-casino-game-image11']",
    LiveOthersGameimage12="[data-hook='live-casino-game-image12']",
    LiveOthersGameimage13="[data-hook='live-casino-game-image13']",
    LiveOthersGameimage14="[data-hook='live-casino-game-image14']",
    LiveOthersGameimage15="[data-hook='live-casino-game-image15']",
    LiveOthersGameimage16="[data-hook='live-casino-game-image16']",
    LiveOthersGameimage17="[data-hook='live-casino-game-image17']",
    LiveOthersGameimage18="[data-hook='live-casino-game-image18']",
    LiveOthersGameimage19="[data-hook='live-casino-game-image19']",
    LiveOthersGameimage20="[data-hook='live-casino-game-image20']",
    LiveOthersGameimage21="[data-hook='live-casino-game-image21']",
    LiveOthersGameimage22="[data-hook='live-casino-game-image22']",
    LiveOthersGameimage23="[data-hook='live-casino-game-image23']",
    LiveOthersGameimage24="[data-hook='live-casino-game-image24']",
    LiveOthersGameimage25="[data-hook='live-casino-game-image25']",
    LiveOthersGameimage26="[data-hook='live-casino-game-image26']",
    LiveOthersGameimage27="[data-hook='live-casino-game-image27']",
    LiveOthersGameimage28="[data-hook='live-casino-game-image28']",
    LiveOthersGameimage29="[data-hook='live-casino-game-image29']",
    LiveOthersGameimage30="[data-hook='live-casino-game-image30']",
    LiveOthersGameimage31="[data-hook='live-casino-game-image31']",
    LiveOthersGameimage32="[data-hook='live-casino-game-image32']",
    LiveOthersGameimage33="[data-hook='live-casino-game-image33']",
    LiveOthersGameimage34="[data-hook='live-casino-game-image34']",
    LiveOthersGameimage35="[data-hook='live-casino-game-image35']",
    LiveOthersGameimage36="[data-hook='live-casino-game-image36']",
    LiveOthersGameimage37="[data-hook='live-casino-game-image37']",
    LiveOthersGameimage38="[data-hook='live-casino-game-image38']",
    LiveOthersGameimage39="[data-hook='live-casino-game-image39']",
    LiveOthersGameimage40="[data-hook='live-casino-game-image40']",
    LiveOthersGameimage41="[data-hook='live-casino-game-image41']",
    LiveOthersGameimage42="[data-hook='live-casino-game-image42']",
    LiveOthersGameimage43="[data-hook='live-casino-game-image43']",
    LiveOthersGameimage44="[data-hook='live-casino-game-image44']",
    LiveOthersGameimage45="[data-hook='live-casino-game-image45']",
    LiveOthersGameimage46="[data-hook='live-casino-game-image46']",
    LiveOthersGameimage47="[data-hook='live-casino-game-image47']",
    LiveOthersGameimage48="[data-hook='live-casino-game-image48']",
    LiveOthersGameimage49="[data-hook='live-casino-game-image49']",
    LiveOthersGameimage50="[data-hook='live-casino-game-image50']",

    # live-casino-info-button1
    Liveinfo1="[data-hook='live-casino-game-info-button1']",
    Liveinfo2="[data-hook='live-casino-game-info-button2']",
    Liveinfo3="[data-hook='live-casino-game-info-button3']",
    Liveinfo4="[data-hook='live-casino-game-info-button4']",
    Liveinfo5="[data-hook='live-casino-game-info-button5']",
    Liveinfo6="[data-hook='live-casino-game-info-button6']",
    Liveinfo7="[data-hook='live-casino-game-info-button7']",
    Liveinfo8="[data-hook='live-casino-game-info-button8']",
    Liveinfo9="[data-hook='live-casino-game-info-button9']",
    Liveinfo10="[data-hook='live-casino-game-info-button10']",
    Liveinfo11="[data-hook='live-casino-game-info-button11']",
    Liveinfo12="[data-hook='live-casino-game-info-button12']",
    Liveinfo13="[data-hook='live-casino-game-info-button13']",
    Liveinfo14="[data-hook='live-casino-game-info-button14']",
    Liveinfo15="[data-hook='live-casino-game-info-button15']",
    Liveinfo16="[data-hook='live-casino-game-info-button16']",
    Liveinfo17="[data-hook='live-casino-game-info-button17']",
    Liveinfo18="[data-hook='live-casino-game-info-button18']",
    Liveinfo19="[data-hook='live-casino-game-info-button19']",
    Liveinfo20="[data-hook='live-casino-game-info-button20']",
    Liveinfo21="[data-hook='live-casino-game-info-button21']",
    Liveinfo22="[data-hook='live-casino-game-info-button22']",
    Liveinfo23="[data-hook='live-casino-game-info-button23']",
    Liveinfo24="[data-hook='live-casino-game-info-button24']",
    Liveinfo25="[data-hook='live-casino-game-info-button25']",
    Liveinfo26="[data-hook='live-casino-game-info-button26']",
    Liveinfo27="[data-hook='live-casino-game-info-button27']",
    Liveinfo28="[data-hook='live-casino-game-info-button28']",
    Liveinfo29="[data-hook='live-casino-game-info-button29']",
    Liveinfo30="[data-hook='live-casino-game-info-button30']",
    Liveinfo31="[data-hook='live-casino-game-info-button31']",
    Liveinfo32="[data-hook='live-casino-game-info-button32']",
    Liveinfo33="[data-hook='live-casino-game-info-button33']",
    Liveinfo34="[data-hook='live-casino-game-info-button34']",
    Liveinfo35="[data-hook='live-casino-game-info-button35']",
    Liveinfo36="[data-hook='live-casino-game-info-button36']",
    Liveinfo37="[data-hook='live-casino-game-info-button37']",
    Liveinfo38="[data-hook='live-casino-game-info-button38']",
    Liveinfo39="[data-hook='live-casino-game-info-button39']",
    Liveinfo40="[data-hook='live-casino-game-info-button40']",
    Liveinfo41="[data-hook='live-casino-game-info-button41']",
    Liveinfo42="[data-hook='live-casino-game-info-button42']",
    Liveinfo43="[data-hook='live-casino-game-info-button43']",
    Liveinfo44="[data-hook='live-casino-game-info-button44']",
    Liveinfo45="[data-hook='live-casino-game-info-button45']",
    Liveinfo46="[data-hook='live-casino-game-info-button46']",
    Liveinfo47="[data-hook='live-casino-game-info-button47']",
    Liveinfo48="[data-hook='live-casino-game-info-button48']",
    Liveinfo49="[data-hook='live-casino-game-info-button49']",
    Liveinfo50="[data-hook='live-casino-game-info-button50']",

    landingothers="[data-hook='live-game-landing-page-breadcrumb-type']"

)
